# Generated by Django 3.0.3 on 2021-11-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211107_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='avatardefault.png', null=True, upload_to='img/%y'),
        ),
    ]
