# Generated by Django 3.0.3 on 2021-11-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='avatar5.jpeg', null=True, upload_to='img/%y'),
        ),
    ]
