# Generated by Django 3.0.3 on 2021-11-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_background_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='img/%y')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='background',
            name='image',
            field=models.ImageField(null=True, upload_to='img/%y'),
        ),
    ]
