# Generated by Django 3.0.3 on 2021-11-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211110_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipments',
            old_name='topic',
            new_name='objname',
        ),
    ]
