# Generated by Django 3.0.3 on 2021-11-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211110_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=50)),
                ('gym', models.CharField(max_length=50)),
            ],
        ),
    ]
