# Generated by Django 3.0.3 on 2021-11-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211110_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='gym',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='services',
            field=models.TextField(null=True),
        ),
    ]
