# Generated by Django 3.0.3 on 2021-11-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20211111_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='sl_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
