# Generated by Django 3.0.3 on 2021-11-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_session_sl_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idcardno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.IntegerField(null=True),
        ),
    ]
